version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --template-file search-photos.yaml --s3-bucket smart-album-nyu --output-template-file search-photos.yaml
artifacts:
  type: zip
  files:
    - search-photos.yaml
