version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - pip install --upgrade pip
      - pip install pipenv --user
      - pipenv install awscli aws-sam-cli
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket nyu-photo-album --output-template-file search-photos.yaml
artifacts:
  files:
    - packaged-template.yml
